// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oksjugfrikzpugwkrirr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rc2p1Z2ZyaWt6cHVnd2tyaXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTExNzAsImV4cCI6MjA2Njc2NzE3MH0.1K80NYafZbh5TIWXoE8W6tRE00CJSz4ia-CJ64GIkzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);